services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    restart: unless-stopped

  qcluster:
    build: .
    command: python manage.py qcluster
    env_file:
      - docker.env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - web
    restart: unless-stopped

  ngrok:
    build: .
    command: ngrok http web:8000 --log=stdout
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    profiles:
      - online
    depends_on:
      - web
    restart: unless-stopped
