# Generated by Django 6.0.5 on 2026-06-04 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('schedule_string', models.CharField(max_length=100)),
                ('location_room', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('layout_variant', models.CharField(choices=[('standard', 'Standard Informational'), ('reading', 'Reading Container Block'), ('quote', 'Border Left Accent Callout')], default='standard', max_length=20)),
                ('status_label', models.CharField(choices=[('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='COMPLETED', max_length=20)),
                ('timestamp_string', models.CharField(max_length=50)),
                ('is_italic', models.BooleanField(default=False)),
                ('has_certificate', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('has_actions', models.BooleanField(default=False)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='archive/covers/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.archivecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUIZ', 'Quiz'), ('ESSAY', 'Essay')], default='QUIZ', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='deadlines/covers/')),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='accounts.academicclass')),
            ],
        ),
    ]
