# Generated by Django 6.0.5 on 2026-06-07 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_archivetag_profiletrait_question_choice_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
