# Generated by Django 6.0.5 on 2026-06-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_academicclass_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='creator',
        ),
        migrations.AddField(
            model_name='quiz',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.academicclass'),
        ),
        migrations.CreateModel(
            name='ClassContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='class_contents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='accounts.academicclass')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
