# Generated by Django 6.0.5 on 2026-06-07 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_quest_creator_quiz_academic_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdocumentsubmission',
            name='instructor_response',
        ),
        migrations.RemoveField(
            model_name='quizdocumentsubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='trait_tag',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='trait_tag',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'quiz')},
            },
        ),
        migrations.DeleteModel(
            name='InstructorQuizResponse',
        ),
        migrations.DeleteModel(
            name='QuizDocumentSubmission',
        ),
    ]
