# Generated by Django 6.0.5 on 2026-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_instructorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicclass',
            name='location_room',
        ),
        migrations.AddField(
            model_name='academicclass',
            name='meeting_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
