# Generated by Django 6.0.5 on 2026-06-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_academicclass_location_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveTag',
        ),
        migrations.DeleteModel(
            name='ProfileTrait',
        ),
    ]
