# Generated by Django 6.0.5 on 2026-07-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_radhia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='radhia',
        ),
    ]
