# Generated by Django 6.0.5 on 2026-07-08 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_radhia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student_avatars/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', null=True)),
                ('inspire_message', models.CharField(blank=True, help_text='A message to inspire others', max_length=280, null=True)),
                ('favorite_quote', models.CharField(blank=True, help_text='Your favorite quote', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
