# Generated by Django 6.0.5 on 2026-07-15 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_role_parentchildlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_names',
            field=models.JSONField(blank=True, default=list, help_text='List of connected parent/guardian names'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True, help_text='Challenge rules displayed to participants')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize_pool_xp', models.IntegerField(default=0, help_text='Bonus XP awarded to winners')),
                ('created_by', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='challenge',
            field=models.ForeignKey(blank=True, help_text='Link to a challenge event (for competition quizzes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.challenge'),
        ),
        migrations.CreateModel(
            name='ChallengeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_links', to='accounts.academicclass')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='accounts.challenge')),
            ],
            options={
                'unique_together': {('challenge', 'academic_class')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='classes',
            field=models.ManyToManyField(related_name='challenges', through='accounts.ChallengeClass', to='accounts.academicclass'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
